import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, basename, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const mode = process.argv[2];
if (process.argv.length !== 3 || !['--check', '--write'].includes(mode)) {
  throw new Error('Usage: node generate.mjs --check|--write');
}

const root = dirname(fileURLToPath(import.meta.url));
const config = ts.getParsedCommandLineOfConfigFile(resolve(root, 'tsconfig.json'), {}, {
  ...ts.sys,
  onUnRecoverableConfigFileDiagnostic: diagnostic => { throw new Error(ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n')); },
});
const output = new Map();
const program = ts.createProgram(config.fileNames, config.options);
const report = diagnostics => {
  console.error(ts.formatDiagnosticsWithColorAndContext(diagnostics, {
    getCurrentDirectory: () => root,
    getCanonicalFileName: path => path,
    getNewLine: () => '\n',
  }));
  process.exit(1);
};
const diagnostics = [...config.errors, ...ts.getPreEmitDiagnostics(program)];
if (diagnostics.length) report(diagnostics);
const emitted = program.emit(undefined, (path, content) => output.set(basename(path), content));
if (emitted.diagnostics.length || emitted.emitSkipped) report(emitted.diagnostics);

const runtime = config.options.rootDir;
const existing = readdirSync(runtime).filter(name => name.endsWith('.js') || name.endsWith('.d.ts'));
const stale = existing.filter(name => !output.has(name));
if (stale.length) throw new Error(`Runtime artifacts without sources: ${stale.join(', ')}`);

for (const [name, emittedContent] of output) {
  let content = emittedContent;
  if (name === '_protocol.js' || name === '_protocol.d.ts') {
    const literal = name.endsWith('.d.ts')
      ? 'export declare const PROTOCOL_VERSION: 0;'
      : 'export const PROTOCOL_VERSION = 0;';
    if (!content.includes(literal)) throw new Error(`Missing protocol version placeholder in ${name}`);
    content = content.replace(literal, literal.replace('0', '{{ protocol_version }}'));
  }
  output.set(name, '/** Generated by tools/js-runtime; edit the matching .ts source. */\n' + content);
}

let mismatches = 0;
for (const [name, content] of output) {
  const destination = resolve(runtime, name);
  if (mode === '--write') {
    writeFileSync(destination, content);
  } else {
    let current;
    try { current = readFileSync(destination, 'utf8').replace(/\r\n/g, '\n'); }
    catch (error) { if (error.code !== 'ENOENT') throw error; }
    if (current !== content) {
      console.error(`Outdated runtime artifact: ${name}`);
      mismatches++;
    }
  }
}
if (mismatches) {
  console.error('Run npm run build from tools/js-runtime and review the generated diff.');
  process.exit(1);
}
console.log(`${mode === '--write' ? 'Wrote' : 'Verified'} ${output.size} runtime artifacts.`);
