/** Generated by tools/js-runtime; edit the matching .ts source. */
import type { EnginePoolOptions } from './_engine.js';
import { EngineProcess } from './_engine.js';
import { IsolationLevel, TransactionClient } from './_transaction.js';
export interface TransactionBatchOperation {
    method: string;
    params: Record<string, unknown>;
}
export interface PlanCacheSectionMetrics {
    entries: number;
    hits: number;
    misses: number;
    evictions: number;
}
export interface EngineMetrics {
    uptimeSeconds: number;
    planCache: {
        capacity: number;
        findUnique: PlanCacheSectionMetrics;
        findMany: PlanCacheSectionMetrics;
    };
    pool: {
        size: number;
        idle: number;
    };
    activeTransactions: number;
    methods: Array<{
        method: string;
        calls: number;
        errors: number;
        totalMs: number;
        maxMs: number;
    }>;
}
export interface NautilusClientOptions {
    migrate?: boolean;
    pool?: EnginePoolOptions;
}
export declare class NautilusClient {
    protected readonly engine: EngineProcess;
    _delegates: Record<string, unknown>;
    constructor(schemaPath: string, options?: NautilusClientOptions);
    connect(): Promise<void>;
    disconnect(): Promise<void>;
    _rpc(method: string, params: Record<string, unknown>): Promise<unknown>;
    _streamRpc(method: string, params: Record<string, unknown>, timeoutMs?: number): AsyncIterable<unknown>;
    protected _startTransaction(timeoutMs?: number, isolationLevel?: IsolationLevel): Promise<string>;
    protected _commitTransaction(txId: string): Promise<void>;
    protected _rollbackTransaction(txId: string): Promise<void>;
    protected _runTransactionBatch(operations: TransactionBatchOperation[], options?: {
        timeout?: number;
        isolationLevel?: IsolationLevel;
    }): Promise<unknown[]>;
    $metrics(options?: {
        reset?: boolean;
    } | undefined): Promise<EngineMetrics>;
    protected _runTransactionCallback<T>(fn: (tx: TransactionClient) => Promise<T>, options?: {
        timeout?: number;
        isolationLevel?: IsolationLevel;
    }): Promise<T>;
}
