/** Generated by tools/js-runtime; edit the matching .ts source. */
/** Rust generation replaces this placeholder with nautilus_protocol::PROTOCOL_VERSION. */
export const PROTOCOL_VERSION = {{ protocol_version }};
