[package]
name = "nautilus-orm"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Nautilus ORM command-line interface"

[package.metadata.wix]
upgrade-guid = "64BA9F55-8641-4574-A3FD-F5EFEBA06E69"
path-guid = "49C69878-ED7C-49EF-8976-2462CCD35AD5"
license = false
eula = false

[[bin]]
name = "nautilus"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
nautilus-schema  = { workspace = true }
nautilus-migrate = { workspace = true }
nautilus-engine  = { workspace = true }
nautilus-codegen = { workspace = true }

tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync"] }

sqlx = { workspace = true, features = ["runtime-tokio-rustls", "any"] }

clap = { workspace = true }

console   = { workspace = true }
indicatif = "0.18.4"

anyhow = { workspace = true }
ctrlc = "3.4"

chrono = { workspace = true, default-features = true }
reqwest = { workspace = true, features = ["json"] }
semver = "1.0"
serde = { workspace = true }
serde_json = { workspace = true }
zip = { version = "2.2", default-features = false, features = ["deflate"] }

[dev-dependencies]
tempfile = { workspace = true }
