//! Embedded Python templates and rendering.

use anyhow::Result;
use tera::{Context, Tera};

/// Python template registry — loaded once at first use.
pub static PYTHON_TEMPLATES: std::sync::LazyLock<Tera> = std::sync::LazyLock::new(|| {
    let mut tera = Tera::default();
    tera.add_raw_templates(vec![
        (
            "files/input_imports.py.tera",
            include_str!("../../../templates/python/files/input_imports.py.tera"),
        ),
        (
            "files/event_imports.py.tera",
            include_str!("../../../templates/python/files/event_imports.py.tera"),
        ),
        (
            "files/aggregate.py.tera",
            include_str!("../../../templates/python/files/aggregate.py.tera"),
        ),
        (
            "files/codec.py.tera",
            include_str!("../../../templates/python/files/codec.py.tera"),
        ),
        (
            "files/codec_imports.py.tera",
            include_str!("../../../templates/python/files/codec_imports.py.tera"),
        ),
        (
            "files/events.py.tera",
            include_str!("../../../templates/python/files/events.py.tera"),
        ),
        (
            "files/facade.py.tera",
            include_str!("../../../templates/python/files/facade.py.tera"),
        ),
        (
            "files/inputs.py.tera",
            include_str!("../../../templates/python/files/inputs.py.tera"),
        ),
        (
            "files/read.py.tera",
            include_str!("../../../templates/python/files/read.py.tera"),
        ),
        (
            "files/write.py.tera",
            include_str!("../../../templates/python/files/write.py.tera"),
        ),
        (
            "model/imports.py.tera",
            include_str!("../../../templates/python/model/imports.py.tera"),
        ),
        (
            "model/runtime_imports.py.tera",
            include_str!("../../../templates/python/model/runtime_imports.py.tera"),
        ),
        (
            "model/record.py.tera",
            include_str!("../../../templates/python/model/record.py.tera"),
        ),
        (
            "model/projection.py.tera",
            include_str!("../../../templates/python/model/projection.py.tera"),
        ),
        (
            "model/metadata.py.tera",
            include_str!("../../../templates/python/model/metadata.py.tera"),
        ),
        (
            "model/input.py.tera",
            include_str!("../../../templates/python/model/input.py.tera"),
        ),
        (
            "model/events.py.tera",
            include_str!("../../../templates/python/model/events.py.tera"),
        ),
        (
            "model/serialize.py.tera",
            include_str!("../../../templates/python/model/serialize.py.tera"),
        ),
        (
            "model/include.py.tera",
            include_str!("../../../templates/python/model/include.py.tera"),
        ),
        (
            "model/decode.py.tera",
            include_str!("../../../templates/python/model/decode.py.tera"),
        ),
        (
            "delegate/state.py.tera",
            include_str!("../../../templates/python/delegate/state.py.tera"),
        ),
        (
            "delegate/find_many.py.tera",
            include_str!("../../../templates/python/delegate/find_many.py.tera"),
        ),
        (
            "delegate/stream.py.tera",
            include_str!("../../../templates/python/delegate/stream.py.tera"),
        ),
        (
            "delegate/find_single.py.tera",
            include_str!("../../../templates/python/delegate/find_single.py.tera"),
        ),
        (
            "delegate/create.py.tera",
            include_str!("../../../templates/python/delegate/create.py.tera"),
        ),
        (
            "delegate/create_many.py.tera",
            include_str!("../../../templates/python/delegate/create_many.py.tera"),
        ),
        (
            "delegate/update.py.tera",
            include_str!("../../../templates/python/delegate/update.py.tera"),
        ),
        (
            "delegate/delete.py.tera",
            include_str!("../../../templates/python/delegate/delete.py.tera"),
        ),
        (
            "delegate/delete_many.py.tera",
            include_str!("../../../templates/python/delegate/delete_many.py.tera"),
        ),
        (
            "delegate/update_many.py.tera",
            include_str!("../../../templates/python/delegate/update_many.py.tera"),
        ),
        (
            "delegate/aggregate.py.tera",
            include_str!("../../../templates/python/delegate/aggregate.py.tera"),
        ),
        (
            "delegate/explain.py.tera",
            include_str!("../../../templates/python/delegate/explain.py.tera"),
        ),
        (
            "delegate/count.py.tera",
            include_str!("../../../templates/python/delegate/count.py.tera"),
        ),
        (
            "delegate/group_by.py.tera",
            include_str!("../../../templates/python/delegate/group_by.py.tera"),
        ),
        (
            "delegate/raw.py.tera",
            include_str!("../../../templates/python/delegate/raw.py.tera"),
        ),
        (
            "delegate/upsert.py.tera",
            include_str!("../../../templates/python/delegate/upsert.py.tera"),
        ),
        (
            "model/exports.py.tera",
            include_str!("../../../templates/python/model/exports.py.tera"),
        ),
        (
            "input/filters.py.tera",
            include_str!("../../../templates/python/input/filters.py.tera"),
        ),
        (
            "input/fields.py.tera",
            include_str!("../../../templates/python/input/fields.py.tera"),
        ),
        (
            "input/includes.py.tera",
            include_str!("../../../templates/python/input/includes.py.tera"),
        ),
        (
            "input/upsert.py.tera",
            include_str!("../../../templates/python/input/upsert.py.tera"),
        ),
        (
            "input/aggregates.py.tera",
            include_str!("../../../templates/python/input/aggregates.py.tera"),
        ),
        (
            "composite_types.py.tera",
            include_str!("../../../templates/python/composite_types.py.tera"),
        ),
        (
            "model_file.py.tera",
            include_str!("../../../templates/python/model_file.py.tera"),
        ),
        (
            "input_types.py.tera",
            include_str!("../../../templates/python/input_types.py.tera"),
        ),
        (
            "enums.py.tera",
            include_str!("../../../templates/python/enums.py.tera"),
        ),
        (
            "client.py.tera",
            include_str!("../../../templates/python/client.py.tera"),
        ),
        (
            "package_init.py.tera",
            include_str!("../../../templates/python/package_init.py.tera"),
        ),
        (
            "models_init.py.tera",
            include_str!("../../../templates/python/models_init.py.tera"),
        ),
        (
            "enums_init.py.tera",
            include_str!("../../../templates/python/enums_init.py.tera"),
        ),
        (
            "errors_init.py.tera",
            include_str!("../../../templates/python/errors_init.py.tera"),
        ),
        (
            "internal_init.py.tera",
            include_str!("../../../templates/python/internal_init.py.tera"),
        ),
        (
            "transaction_init.py.tera",
            include_str!("../../../templates/python/transaction_init.py.tera"),
        ),
        (
            "events.py.tera",
            include_str!("../../../templates/python/events.py.tera"),
        ),
    ])
    .expect("embedded Python templates must parse");
    tera
});

pub(super) fn render(template: &str, ctx: &Context) -> Result<String> {
    crate::template::render(&PYTHON_TEMPLATES, template, ctx)
}
