//! Embedded Rust templates and rendering.

use anyhow::Result;
use tera::{Context, Tera};

pub static TEMPLATES: std::sync::LazyLock<Tera> = std::sync::LazyLock::new(|| {
    let mut tera = Tera::default();
    tera.add_raw_templates(vec![
        (
            "model/facade.tera",
            include_str!("../../templates/rust/model/facade.tera"),
        ),
        (
            "delegate/operation.tera",
            include_str!("../../templates/rust/delegate/operation.tera"),
        ),
        (
            "delegate/nested_input.tera",
            include_str!("../../templates/rust/delegate/nested_input.tera"),
        ),
        (
            "delegate/write_input.tera",
            include_str!("../../templates/rust/delegate/write_input.tera"),
        ),
        (
            "delegate/aggregate_input.tera",
            include_str!("../../templates/rust/delegate/aggregate_input.tera"),
        ),
        (
            "delegate/aggregate_output.tera",
            include_str!("../../templates/rust/delegate/aggregate_output.tera"),
        ),
        (
            "delegate/aggregate_decode.tera",
            include_str!("../../templates/rust/delegate/aggregate_decode.tera"),
        ),
        (
            "delegate/write_filter.tera",
            include_str!("../../templates/rust/delegate/write_filter.tera"),
        ),
        (
            "delegate/state.tera",
            include_str!("../../templates/rust/delegate/state.tera"),
        ),
        (
            "delegate/read.tera",
            include_str!("../../templates/rust/delegate/read.tera"),
        ),
        (
            "delegate/projection.tera",
            include_str!("../../templates/rust/delegate/projection.tera"),
        ),
        (
            "delegate/stream.tera",
            include_str!("../../templates/rust/delegate/stream.tera"),
        ),
        (
            "delegate/create.tera",
            include_str!("../../templates/rust/delegate/create.tera"),
        ),
        (
            "delegate/create_many.tera",
            include_str!("../../templates/rust/delegate/create_many.tera"),
        ),
        (
            "delegate/update.tera",
            include_str!("../../templates/rust/delegate/update.tera"),
        ),
        (
            "delegate/delete.tera",
            include_str!("../../templates/rust/delegate/delete.tera"),
        ),
        (
            "delegate/delete_many.tera",
            include_str!("../../templates/rust/delegate/delete_many.tera"),
        ),
        (
            "delegate/count.tera",
            include_str!("../../templates/rust/delegate/count.tera"),
        ),
        (
            "delegate/update_many.tera",
            include_str!("../../templates/rust/delegate/update_many.tera"),
        ),
        (
            "delegate/delete_many_count.tera",
            include_str!("../../templates/rust/delegate/delete_many_count.tera"),
        ),
        (
            "delegate/aggregate.tera",
            include_str!("../../templates/rust/delegate/aggregate.tera"),
        ),
        (
            "delegate/upsert.tera",
            include_str!("../../templates/rust/delegate/upsert.tera"),
        ),
        (
            "model/imports.tera",
            include_str!("../../templates/rust/model/imports.tera"),
        ),
        (
            "model/decode.tera",
            include_str!("../../templates/rust/model/decode.tera"),
        ),
        (
            "model/body.tera",
            include_str!("../../templates/rust/model/body.tera"),
        ),
        (
            "read/ordering.tera",
            include_str!("../../templates/rust/read/ordering.tera"),
        ),
        (
            "read/builder.tera",
            include_str!("../../templates/rust/read/builder.tera"),
        ),
        (
            "read/execute.tera",
            include_str!("../../templates/rust/read/execute.tera"),
        ),
        (
            "columns_struct.tera",
            include_str!("../../templates/rust/columns_struct.tera"),
        ),
        (
            "column_impl.tera",
            include_str!("../../templates/rust/column_impl.tera"),
        ),
        (
            "create.tera",
            include_str!("../../templates/rust/create.tera"),
        ),
        (
            "create_many.tera",
            include_str!("../../templates/rust/create_many.tera"),
        ),
        (
            "delegate.tera",
            include_str!("../../templates/rust/delegate.tera"),
        ),
        (
            "delete.tera",
            include_str!("../../templates/rust/delete.tera"),
        ),
        ("enum.tera", include_str!("../../templates/rust/enum.tera")),
        (
            "find_many.tera",
            include_str!("../../templates/rust/find_many.tera"),
        ),
        (
            "from_row_impl.tera",
            include_str!("../../templates/rust/from_row_impl.tera"),
        ),
        (
            "model_file.tera",
            include_str!("../../templates/rust/model_file.tera"),
        ),
        (
            "lib_rs.tera",
            include_str!("../../templates/rust/lib_rs.tera"),
        ),
        (
            "model_struct.tera",
            include_str!("../../templates/rust/model_struct.tera"),
        ),
        (
            "update.tera",
            include_str!("../../templates/rust/update.tera"),
        ),
        (
            "composite_type.tera",
            include_str!("../../templates/rust/composite_type.tera"),
        ),
    ])
    .expect("embedded Rust templates must parse");
    tera
});

pub(super) fn render(template: &str, ctx: &Context) -> Result<String> {
    crate::template::render(&TEMPLATES, template, ctx)
}
